### ISSUE TITLE
Is it possible and better to require laravel-fly?

### ISSUE THREAD

**Issue by scil** [tamer-hassan/october-fly#1]
As an independent fork,  codes can not be keep lastest with laravel-fly.

So is it possible to use require in composer.json
```
  "require": {
    "scil/laravel-fly": "dev-master",
  },
```

**Comment by tamer-hassan** [comment]
of course, this would be the ideal way to go.
october-fly 0.0.1 - 0.0.2 are just really alphas to quickly demo a lean version of laravel-fly, i.e. without pulling in unneeded laravel 5.6 files as well, since octobercms 1.0.* is in parity with 5.5.* only.

Most importantly, there exists no `\App` namespace in OctoberCMS as in a standard laravel app, and that is referenced in many places in laravel-fly code. I can't remember off the top of my head (and unfortunately didn't keep a log) of where it had to be removed or replaced. but for example here: https://github.com/scil/LaravelFly/blob/master/src/LaravelFly/Server/Traits/Laravel.php#L51-L55
` \App\Console\Kernel` and `\App\Exceptions\Handler`
and here: https://github.com/scil/LaravelFly/blob/master/src/LaravelFly/Server/Common.php#L176
`App\Http\Kernel`
also, current logic of how laravel-fly needs edit to `App\Http\Kernel` to let same code work with php-fpm and swoole cannot be easily applied to october as october http kernel lives in vendor dir.
Therefore, I had to change `LaravelFly\Server\Common::parseOptions` logic to let it work same for php-fpm/swoole without requiring edit of kernel or bootstrap/app
so lots to override if using laravel-fly in composer require.

**Comment by scil** [comment]
Thank you for reply. 

There is an option in fly.conf.php
```
    'server' => \LaravelFly\Server\HttpServer::class,
```
I think it can help make changed to `LaravelFly\Server\Common` or `LaravelFly\Server\Traits\...` whoes use is totally in \LaravelFly\Server\HttpServer.

Maybe you can extend that server and make changes.

**Comment by tamer-hassan** [comment]
thanks @scil . Then I'll do that.

**Comment by tamer-hassan** [comment]
october-fly v0.0.3 now requires [scil/laravel-fly](https://github.com/scil/LaravelFly)

**Comment by honglibin** [comment]
why when i execute `php vendor/tamerhassan/october-fly/bin/fly start` ,the cli display error with `failed to open stream: No such file or directory in /www/wwwroot/zdd/vendor/tamerhassan/october-fly/src/OctoberFly/Server/Common.php on line 226`. wait for your help, thanks very much
